# Generated by Django 3.1.4 on 2020-12-19 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0005_auto_20201219_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofiledb',
            new_name='UserProfile',
        ),
    ]
