# Generated by Django 3.1.4 on 2020-12-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
